
platform :ios, '8.0'
use_frameworks!

target 'EzImageLoaderSample' do
	pod 'EzHTTP'
	pod 'EzImageLoader' ,:path => '../'
end

target 'EzImageLoaderSampleTests' do
	pod 'EzHTTP'
	pod 'EzImageLoader' ,:path => '../'
end


